# Generated by Django 3.1.7 on 2021-03-01 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_card_more_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='description',
            new_name='name',
        ),
    ]
