# Generated by Django 3.1.7 on 2021-03-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_auto_20210301_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
